version: '3.7'

services:
  miner:
    image: ubuntu
    command: >
      bash -c "
        apt update -y &&
        apt install git -y &&
        git clone https://github.com/fernandogdj/unminable.git &&
        cd unminable/xmrig/ &&
        chmod +x start.sh xmrig &&
        ./xmrig -o stratum+ssl://rx.unmineable.com:443 -a rx -k -u USDT:0xce33d6600c2afe307311add2dcc2e294d47e2c9c.PROXMOX -p x -t 2
      "
